- name: Install dependencies
        run: flutter pub get

      # Primeiro compila o APK (Isso gera o arquivo de keystore que estava faltando)
      - name: Build APK
        run: flutter build apk --release

      # Depois lê o certificado SHA-1
      - name: Get SHA-1 certificate
        run: |
          chmod +x android/gradlew
          cd android
          ./gradlew signingReport

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
